### ISSUE TITLE
Error when running job "Get nodes"

### ISSUE THREAD

**Issue by yregaieg** [fcorti/alfresco-audit-analysis-reporting#47]
The backing whebscript for this job called "GetNodesModifiedAfterWebScript" seems to fail on this line : 

https://github.com/fcorti/alfresco-audit-analysis-reporting/blob/master/Alfresco/Alfresco-EE-v5.1/AAAR-Alfresco-EE-v5.1-Repository/src/main/java/com/fcorti/aaar/GetNodesModifiedAfterWebScript.java#L137 

with this exception
```
 2017-01-30 01:06:31,777  ERROR [extensions.webscripts.AbstractRuntime] [http-apr-8080-exec-15] Exception from executeScript - redirecting to status template error: 00300017 Wrapped Exception (with status template): A namespace prefix is not registered for uri dl
 org.springframework.extensions.webscripts.WebScriptException: 00300017 Wrapped Exception (with status template): A namespace prefix is not registered for uri dl
	at org.springframework.extensions.webscripts.AbstractWebScript.createStatusException(AbstractWebScript.java:1138)
	at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:171)
	at org.alfresco.repo.web.scripts.RepositoryContainer$3.execute(RepositoryContainer.java:519)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:464)
	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:587)
	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:656)
	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:428)
	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:308)
	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:382)
	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:210)
	at org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:132)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.alfresco.module.aosmodule.service.ContextRootFilter.doFilter(ContextRootFilter.java:93)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2403)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.alfresco.service.namespace.NamespaceException: A namespace prefix is not registered for uri dl
	at org.alfresco.util.ISO9075.getXPathName(ISO9075.java:334)
	at org.alfresco.service.cmr.repository.Path$ChildAssocElement.createElementString(Path.java:428)
	at org.alfresco.service.cmr.repository.Path$ChildAssocElement.getPrefixedString(Path.java:389)
	at org.alfresco.service.cmr.repository.Path.toPrefixString(Path.java:190)
	at com.fcorti.aaar.GetNodesModifiedAfterWebScript.executeImpl(GetNodesModifiedAfterWebScript.java:137)
	at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:64)
	... 36 more
```

And it seems that the namespace service is having a problem resolving some paths, it can be related to some unicode characters in node names or orphaned nodes (nodes without any parent)
I will try to dig deeper into this, and if it turned out an issue with orphaned nodes, I think I should surround this by a try catch and fallback to UNKNOWN in case the path was not resolved

What do you think ?

**Comment by fcorti** [comment]
I often face similar problems (not exactly this but other related to the repository).
In my experience it happens when something is not expected as a "standard" configuration.
In this case, seems to be the "dl" namespace is not recognise... mmmm, strange.
I suggest to debug the source code.
I could help if you request.

**Comment by yregaieg** [comment]
This turned out to be an error related to a wrong URI in the qname of an association to datalist.
It should be resolved by fixing the alfresco code bootstrapping these datalists, and recreating the offending items!
